name: svmegn
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
        tsan: [ON, OFF]
        exclude:
          - asan: ON
            tsan: ON
          - asan: ON
            os: windows-latest
          - tsan: ON
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: run tests
        run: |
          python3 bootstrap.py --build_type ${{ matrix.config }}
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dsvmegn_build_tests=ON -Dsvmegn_enable_asan=${{ matrix.asan }} -Dsvmegn_enable_tsan=${{ matrix.tsan }} .
          cmake --build . -j 4 --config ${{ matrix.config }}
          ctest --verbose
